/* generated by dia/codegen.py */
/*accelerometer connections*/
class Accelerometer 
{
public:
	 get_accel (Point3D acc);
};

/*(NULL)*/
class Point 
{
public:
	float X;
	float Y;
};

/*communication for robot class*/
class Communication 
{
public:
	void move_cmd (Point target_position);
	Point get_current_position (Point position);
private:
	Point position;
};

/*robot class*/
class Robot 
{
public:
	void move_to (Point target_position);
private:
	Point position_current;
};

/*Encoder connections*/
class Encoder 
{
public:
	 get_ticks (Point ticks);
};

/*motor arrangement*/
class Actuation 
{
public:
	void set_motor (WHEEL motor,
	                int speed);
private:
	float wheel_saparator;
	float wheel_radius;
};

/*robot navigation class*/
class Navigation 
{
public:
	void move_to (Point target_position);
private:
	 calculate (Point position_current,
	            Point position_target,
	            Vel_Dir velocity_and_direction);
};

/*Gyroscope connections*/
class Gyroscope 
{
public:
	 get_angle_rate (Point3D gyr);
};

/*(NULL)*/
class Point3D 
{
public:
	float X;
	float Y;
	float Z;
};

